import { readFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { renderSeoHead } from './structured-data.js'
import { DEFAULT_LOCALE, LOCALE_META, LOCALES } from './locales.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const I18N_DIR = resolve(HERE, '../src/i18n')

/**
 * SEO footer link clusters, shared with the blog.
 *
 * Generated by scripts/build-footer-articles.mjs from the blog repo, so the
 * "which articles get promoted" decision lives in exactly one place
 * (apps/blog lib/footer-links.ts) instead of drifting between two apps.
 */
const FOOTER_ARTICLES = JSON.parse(
  readFileSync(resolve(I18N_DIR, 'footer-articles.json'), 'utf-8'),
)

/** Column headings per locale. Falls back to English for locales not listed. */
const FOOTER_GROUP_LABELS = {
  glp1Start: { en: 'STARTING GLP-1', ko: 'GLP-1 시작하기', ja: 'GLP-1 をはじめる', 'zh-tw': '開始使用 GLP-1', 'zh-cn': '开始使用 GLP-1', es: 'EMPEZAR CON GLP-1', de: 'GLP-1 STARTEN', fr: 'DÉBUTER LE GLP-1', pt: 'COMEÇAR COM GLP-1', it: 'INIZIARE CON GLP-1', id: 'MEMULAI GLP-1' },
  sideEffects: { en: 'SIDE EFFECT GUIDES', ko: '부작용 가이드', ja: '副作用ガイド', 'zh-tw': '副作用指南', 'zh-cn': '副作用指南', es: 'EFECTOS SECUNDARIOS', de: 'NEBENWIRKUNGEN', fr: 'EFFETS SECONDAIRES', pt: 'EFEITOS COLATERAIS', it: 'EFFETTI COLLATERALI', id: 'PANDUAN EFEK SAMPING' },
  compare: { en: 'COMPARE MEDICATIONS', ko: '약물 비교', ja: '薬の比較', 'zh-tw': '藥物比較', 'zh-cn': '药物比较', es: 'COMPARAR MEDICAMENTOS', de: 'MEDIKAMENTE VERGLEICHEN', fr: 'COMPARER LES TRAITEMENTS', pt: 'COMPARAR MEDICAMENTOS', it: 'CONFRONTA I FARMACI', id: 'BANDINGKAN OBAT' },
  interactions: { en: 'DRUG INTERACTIONS', ko: '병용·상호작용', ja: '併用・相互作用', 'zh-tw': '併用與交互作用', 'zh-cn': '联用与相互作用', es: 'INTERACCIONES', de: 'WECHSELWIRKUNGEN', fr: 'INTERACTIONS', pt: 'INTERAÇÕES', it: 'INTERAZIONI', id: 'INTERAKSI OBAT' },
  afterGlp1: { en: 'AFTER GLP-1', ko: '중단 후 유지', ja: '中止後の維持', 'zh-tw': '停藥後維持', 'zh-cn': '停药后维持', es: 'DESPUÉS DEL GLP-1', de: 'NACH GLP-1', fr: 'APRÈS LE GLP-1', pt: 'DEPOIS DO GLP-1', it: 'DOPO IL GLP-1', id: 'SETELAH GLP-1' },
  conditions: { en: 'FOR YOUR SITUATION', ko: '상황별 가이드', ja: '状況別ガイド', 'zh-tw': '依情況查看', 'zh-cn': '按情况查看', es: 'SEGÚN TU CASO', de: 'FÜR IHRE SITUATION', fr: 'SELON VOTRE CAS', pt: 'PARA O SEU CASO', it: 'IN BASE ALLA TUA SITUAZIONE', id: 'SESUAI KONDISI ANDA' },
  tracker: { en: 'TRACKING BY MEDICATION', ko: '약물별 기록', ja: '薬剤別の記録', 'zh-tw': '依藥物追蹤', 'zh-cn': '按药物追踪', es: 'SEGUIMIENTO POR MEDICAMENTO', de: 'TRACKING NACH MEDIKAMENT', fr: 'SUIVI PAR TRAITEMENT', pt: 'ACOMPANHAMENTO POR MEDICAMENTO', it: 'MONITORAGGIO PER FARMACO', id: 'PELACAKAN PER OBAT' },
  alternatives: { en: 'APP ALTERNATIVES', ko: '앱 대안 비교', ja: 'アプリの代替候補', 'zh-tw': '應用程式替代方案', 'zh-cn': '应用替代方案', es: 'ALTERNATIVAS DE APPS', de: 'APP-ALTERNATIVEN', fr: 'ALTERNATIVES AUX APPS', pt: 'ALTERNATIVAS DE APPS', it: 'ALTERNATIVE ALLE APP', id: 'ALTERNATIF APLIKASI' },
}

// 블로그는 2026-09 에 www.aihavit.com/blog 로 들어왔다(서브도메인은 링크
// 권위를 물려받지 못해 옮겼다). 같은 오리진이므로 절대 URL 대신 경로를 쓴다.
const BLOG = '/blog'

/**
 * Render the SEO cluster block for one locale.
 *
 * 링크 언어는 **링크마다** 정한다. 생성기가 라벨을 넣어주는 건 그 언어에
 * 실제 번역이 있을 때뿐이라, 라벨 유무가 곧 원문 존재 여부다. 번역이 없는데
 * `/blog/<locale>/<slug>` 로 보내면 블로그가 영어 본문을 폴백으로 띄우면서
 * noindex + canonical→en 을 달기 때문에, 홈페이지가 가진 링크 권위가
 * 색인도 안 되는 URL 로 새어나간다. 그런 링크만 영어로 보낸다.
 *
 * (예전엔 언어 단위로 갈랐다 — 블로그가 en/ko/ja/zh-tw 만 서빙하고 나머지가
 *  410 이던 시절의 로직이다. 2026-09 에 10개 언어를 되돌리면서 바뀌었다.)
 */
/**
 * 마케팅 사이트 로케일 → 블로그 언어. 두 집합의 디렉터리 이름이 다른 둘만 적는다.
 * 이게 없어서 `pt` 와 `zh-cn` 홈은 블로그 링크 51개가 전부 영어로 나갔다 —
 * `/blog/pt-br` 과 `/blog/zh` 는 멀쩡히 살아 있는데도.
 */
const BLOG_LANG_OF = { 'zh-cn': 'zh', pt: 'pt-br' }

/** 이 홈 로케일이 링크할 블로그 언어 (블로그에 없는 언어면 영어). */
function blogLangOf(locale) {
  const mapped = BLOG_LANG_OF[locale] ?? locale
  return FOOTER_ARTICLES.blogLangs.includes(mapped) ? mapped : DEFAULT_LOCALE
}

/**
 * index.html 의 블로그 링크(`/blog/`)를 로케일 블로그로 직접 보낸다.
 * `/blog/` 는 308(슬래시) → `/blog` 302(Accept-Language) → `/blog/<lang>` 3홉이고,
 * 크롤러는 Accept-Language 를 안 보내서 /ko/ 홈에서 따라가도 영어 블로그로 간다.
 */
function localizeBlogLinks(html, locale) {
  return html.replace(/href="\/blog\/"/g, `href="${BLOG}/${blogLangOf(locale)}"`)
}

function renderFooterArticles(locale) {
  const blogLang = blogLangOf(locale)
  const cols = FOOTER_ARTICLES.groups
    .map((g) => {
      // 라벨이 없으면 예전에는 키(`tracker`)가 그대로 노출됐다. 조용히 나쁜 값을
      // 서빙하느니 빌드를 세운다 — 생성기가 그룹을 늘릴 때마다 여기도 늘어나야 한다.
      const heading =
        FOOTER_GROUP_LABELS[g.key]?.[locale] ?? FOOTER_GROUP_LABELS[g.key]?.[DEFAULT_LOCALE]
      if (!heading) {
        throw new Error(
          `footer group '${g.key}' has no label in FOOTER_GROUP_LABELS (plugins/i18n-html.js)`,
        )
      }
      const links = g.links
        .map((l) => {
          const native = l.labels[blogLang]
          const label = native ?? l.labels[DEFAULT_LOCALE]
          if (!label) return ''
          const lang = native ? blogLang : DEFAULT_LOCALE
          return `<a href="${BLOG}/${lang}/${l.slug}">${label}</a>`
        })
        .join('')
      return `<div class="footer__col"><p class="eyebrow">${heading}</p>${links}</div>`
    })
    .join('')
  return `<div class="footer__seo">${cols}</div>`
}

/**
 * Locales served by this site.
 *
 * The table itself lives in plugins/locales.js so that middleware.js (Vercel
 * Routing Middleware, edge runtime) can import the same list — this module
 * readFileSync's footer-articles.json at import time and therefore cannot be
 * loaded there. Re-exported here so plugins/sitemap.js and existing callers
 * keep their import path.
 *
 * Note for SEO: the blog currently serves only en/ja/ko/zh-tw and 410s its other
 * language paths to concentrate crawl budget on a young domain. The homepage is
 * a single page rather than ~1k articles per language, so the thin-content risk
 * that drove that decision does not apply here in the same way — but if index
 * coverage stalls, plugins/locales.js is the lever to pull back.
 */
export { DEFAULT_LOCALE, LOCALE_META, LOCALES }

const SITE = 'https://www.aihavit.com'

function loadDict(locale) {
  return JSON.parse(readFileSync(resolve(I18N_DIR, `${locale}.json`), 'utf-8'))
}

/**
 * Locales that actually have a translation file. LOCALE_META lists every locale
 * the site intends to serve; a locale without JSON is simply not emitted rather
 * than failing the build, so languages can land one at a time.
 */
export function translatedLocales() {
  const present = new Set(
    readdirSync(I18N_DIR).filter((f) => f.endsWith('.json')).map((f) => f.replace(/\.json$/, '')),
  )
  return LOCALES.filter((l) => l === DEFAULT_LOCALE || present.has(l))
}

/** Absolute site URL for a locale's home page. */
export function localeUrl(locale) {
  return locale === DEFAULT_LOCALE ? `${SITE}/` : `${SITE}/${locale}/`
}

/**
 * Swap every `data-i18n` element's inner HTML for the localized string.
 *
 * Values may contain inline markup (`<br>`, the underline `<span>`, the mailto
 * link), which is why this replaces innerHTML wholesale rather than text only —
 * translations carry their own markup. Only leaf elements are keyed (see the
 * instrumentation in index.html), so the non-greedy match cannot swallow a
 * nested element of the same tag.
 */
function translateBody(html, dict) {
  let missing = 0
  const out = html.replace(
    /<([a-z0-9]+)([^>]*\sdata-i18n="([^"]+)"[^>]*)>([\s\S]*?)<\/\1>/gi,
    (whole, tag, attrs, key, inner) => {
      const value = dict[key]
      if (value === undefined) {
        missing++
        return whole
      }
      return `<${tag}${attrs}>${value}</${tag}>`
    },
  )
  return { html: out, missing }
}

/**
 * Rewrite <html lang>, <title>, meta description, canonical + hreflang set, and
 * append the Open Graph / JSON-LD block.
 *
 * `baseHtml` is the untranslated index.html: the default locale keeps its
 * strings in the markup rather than a dictionary, so the schema builder needs
 * the original to resolve a key when `dict` is empty.
 */
function translateHead(html, locale, dict, baseHtml) {
  const meta = LOCALE_META[locale]
  // Arabic and Hebrew need dir="rtl"; every other locale must not carry a stale
  // dir attribute, so the whole <html …> tag is rewritten rather than patched.
  const dirAttr = meta.dir ? ` dir="${meta.dir}"` : ''
  html = html.replace(/<html\b[^>]*>/i, `<html lang="${meta.htmlLang}"${dirAttr}>`)

  if (dict.__title) {
    html = html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${dict.__title}</title>`)
  }
  if (dict.__description) {
    html = html.replace(
      /<meta\s+name="description"\s+content="[^"]*"\s*\/?>/i,
      `<meta name="description" content="${dict.__description}" />`,
    )
  }

  // Strip any previously-injected block so re-runs stay idempotent.
  html = html.replace(/\s*<!-- i18n:alternates -->[\s\S]*?<!-- \/i18n:alternates -->/i, '')
  html = html.replace(/\s*<!-- i18n:seo -->[\s\S]*?<!-- \/i18n:seo -->/i, '')

  const links = [
    `    <link rel="canonical" href="${localeUrl(locale)}" />`,
    ...translatedLocales().map(
      (l) =>
        `    <link rel="alternate" hreflang="${LOCALE_META[l].hreflang}" href="${localeUrl(l)}" />`,
    ),
    `    <link rel="alternate" hreflang="x-default" href="${localeUrl(DEFAULT_LOCALE)}" />`,
  ].join('\n')

  // Whatever survived the rewrites above is what the page actually says, so the
  // social tags and the schema read those final values back rather than
  // re-deriving them from the dictionary and risking a mismatch.
  const title = plainText((/<title>([\s\S]*?)<\/title>/i.exec(html) || [, ''])[1])
  const description = (/<meta\s+name="description"\s+content="([^"]*)"/i.exec(html) || [, ''])[1]

  const seo = renderSeoHead({
    locale,
    dict,
    baseHtml,
    title,
    description,
    url: localeUrl(locale),
    localeMeta: meta,
  })

  return html.replace(
    /<\/head>/i,
    `    <!-- i18n:alternates -->\n${links}\n    <!-- /i18n:alternates -->\n` +
      `    <!-- i18n:seo -->\n${seo}\n    <!-- /i18n:seo -->\n  </head>`,
  )
}

/** Entity-decoded, tag-free text — a dictionary <title> may carry entities. */
function plainText(str) {
  return str
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;|&apos;/g, "'")
    .replace(/\s+/g, ' ')
    .trim()
}

/** Swap the placeholder in index.html for this locale's cluster block. */
function injectFooterArticles(html, locale) {
  return html.replace(
    /<!-- i18n:footer-articles -->[\s\S]*?<!-- \/i18n:footer-articles -->/i,
    `<!-- i18n:footer-articles -->${renderFooterArticles(locale)}<!-- /i18n:footer-articles -->`,
  )
}

/**
 * Href for one entry of the language menu.
 *
 * Everything points at its own directory except English, which is the root —
 * and the root is what middleware.js forwards to the device language. A visitor
 * who landed on /ko/ from a search result carries no hv_lang cookie yet, so a
 * bare `/` here would forward them right back and the menu would look broken.
 * `?lang=en` is the explicit override the middleware honours; the root page's
 * own entry stays a clean `/` because being there already sets the cookie.
 */
function langHref(target, current) {
  if (target !== DEFAULT_LOCALE) return `/${target}/`
  return current === DEFAULT_LOCALE ? '/' : '/?lang=en'
}

/**
 * Build the language menu. index.html ships a placeholder list; with 34 locales
 * it has to be generated rather than hand-maintained, and generating it per page
 * lets the current locale be marked with aria-current.
 */
function renderLangMenu(html, locale) {
  const items = translatedLocales().map((l) => {
    const cur = l === locale ? ' aria-current="true"' : ''
    return `<a href="${langHref(l, locale)}"${cur}>${LOCALE_META[l].native}</a>`
  }).join('')
  return html.replace(
    /(<div class="lang-switch__menu">)[\s\S]*?(<\/div>)/i,
    `$1${items}$2`,
  )
}

/** Root-relative asset paths already work from /<locale>/, so nothing to rewrite. */
export function renderLocale(baseHtml, locale) {
  const dict = locale === DEFAULT_LOCALE ? {} : loadDict(locale)
  const { html, missing } = locale === DEFAULT_LOCALE
    ? { html: baseHtml, missing: 0 }
    : translateBody(baseHtml, dict)
  const withHead = renderLangMenu(translateHead(html, locale, dict, baseHtml), locale)
  return { html: localizeBlogLinks(injectFooterArticles(withHead, locale), locale), missing }
}

export default function i18nHtml() {
  return {
    name: 'havit-i18n-html',
    enforce: 'post',

    /**
     * Dev: serve every locale from the same source index.html.
     *
     * The root goes through renderLocale too even though English needs no
     * dictionary — the hreflang set, the language menu and the footer link
     * clusters are all injected there, so skipping it would make the page you
     * review locally differ from the one that ships.
     */
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const path = (req.url || '').split('?')[0]
        const m = /^\/([a-z-]+)\/?$/.exec(path)
        const locale = path === '/' ? DEFAULT_LOCALE : m && m[1]
        if (!locale || !translatedLocales().includes(locale)) return next()
        try {
          const raw = readFileSync(resolve(HERE, '../index.html'), 'utf-8')
          const url = locale === DEFAULT_LOCALE ? '/' : `/${locale}/`
          const transformed = await server.transformIndexHtml(url, raw)
          const { html, missing } = renderLocale(transformed, locale)
          if (missing) server.config.logger.warn(`[i18n] ${locale}: ${missing} missing keys`)
          res.setHeader('Content-Type', 'text/html')
          res.end(html)
        } catch (e) {
          next(e)
        }
      })
    },

    /** Build: emit one extra HTML file per non-default locale. */
    generateBundle(_options, bundle) {
      const index = bundle['index.html']
      if (!index) return
      const base = typeof index.source === 'string' ? index.source : index.source.toString()

      // The default locale still needs canonical + hreflang injected.
      const root = renderLocale(base, DEFAULT_LOCALE)
      index.source = root.html

      for (const locale of translatedLocales()) {
        if (locale === DEFAULT_LOCALE) continue
        const { html, missing } = renderLocale(base, locale)
        if (missing) this.warn(`[i18n] ${locale}: ${missing} keys missing from src/i18n/${locale}.json`)
        this.emitFile({ type: 'asset', fileName: `${locale}/index.html`, source: html })
      }
    },
  }
}

/** Sanity helper for scripts: which locale JSON files exist. */
export function availableLocales() {
  return readdirSync(I18N_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''))
}
